### ISSUE TITLE
Design graphic for battery gauge

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-design#414]
In order to add some variation to our Rapid Router levels, we would like to create some new elements based on the environment. This task is looking at the petrol guage and creating an electric equivalent.

Please research the element first to understand how it works with limited fuel levels.

Use either Illustrator or Figma to create your working and SVG files.

Note: We have a Desktop first approach as most users are on Desktop.

**Comment by ligiaolmos** [comment]
<img width="1071" alt="Electric_battery_gauge_1" src="https://github.com/ocadotechnology/codeforlife-design/assets/163847431/9de57654-7afb-4a60-a26e-6c9c70866f37">
![Electric_battery_gauge_all](https://github.com/ocadotechnology/codeforlife-design/assets/163847431/30996ccf-433f-45c6-9a12-6de24f330ef4)
Hi Laura, here is a proposal for the electric battery gauge. Let me know if this works for you. Thanks

**Comment by ligiaolmos** [comment]
![Electric_battery_gauge_all](https://github.com/ocadotechnology/codeforlife-design/assets/163847431/21bf3c73-6b9d-49bc-9356-7bdbf7a0f941)

**Comment by ligiaolmos** [comment]
![Electric_battery_gauge_all](https://github.com/ocadotechnology/codeforlife-design/assets/163847431/9d4c0edf-36b9-4c11-91fd-967e125fd188)

**Comment by lauracumming** [comment]
Great! I think these will work well. @faucomte97 @SKairinos Do we need a specific number of units for this to slot in easily, ie does it need to have the same amount as the petrol gauge, if so, how many is that?

**Comment by ligiaolmos** [comment]
Ok, will wait for the comment to finish, review and polish the asset for the final version

**Comment by ligiaolmos** [comment]
[Electric_gauge.zip](https://github.com/ocadotechnology/codeforlife-design/files/15487019/Electric_gauge.zip)
Hi, Thanks for the references. I'm uploading the electric gauge in layers in SVG. Also, I'm sending the font Lilita in case you need. Is this enough to be able to animate? Let me know if I'm missing anything @lauracumming @SKairinos . Otherwise I can rethink the counter to be in 1 piece (like a loading circle). Let me know. Thanks!

**Comment by ligiaolmos** [comment]
[Electric_gauge.zip](https://github.com/ocadotechnology/codeforlife-design/files/15487172/Electric_gauge.zip)

**Comment by ligiaolmos** [comment]
[Electric_gauge.zip](https://github.com/ocadotechnology/codeforlife-design/files/15487222/Electric_gauge.zip)

**Comment by SKairinos** [comment]
Thank you for this! Could I kindly request one change that will help us animate this better. Rather than creating 10 segments of a circle in the SVG, create one circle element with 10 dividers overlaid.

This way, we can animate the single circle increasing and decreasing. The 10 dividers would just be fixed in place on top of the animated circle.

**Comment by ligiaolmos** [comment]
Sure! No problem. I'm on it

**Comment by ligiaolmos** [comment]
![Electric_gauge](https://github.com/ocadotechnology/codeforlife-design/assets/163847431/86422d5e-8c22-49d8-ae26-871d01c8df63)
Hi @SKairinos here is the asset in 1 piece, is in layers, let me know if you need anything else

**Comment by SKairinos** [comment]
perfect, ty!

**Comment by lauracumming** [comment]
Outlined the font and re-exported the SVG: https://drive.google.com/file/d/1VEz_P5A22vJLGuq69eT8xeyY1c8xX2Hg/view?usp=drive_link
